blank_issues_enabled: true
contact_links:
  - name: SMU Open Source
    url: https://github.com/smu-open-source
    about: Visit the SMU Open Source organization
  - name: Documentation
    url: https://github.com/smu-open-source/labtest-archiver/tree/main/docs
    about: Check out our documentation for guides and tutorials
